version: "3.8"

services:
  app:
    container_name: pyds-app
    build: .
    command: scrapy crawl quotes
    working_dir: /code/
    volumes:
      - ./:/code
    networks:
      - pyds
networks:
  pyds:
    driver: bridge
